name: 'Setup Environment'
description: 'Sets up Python, Poetry, and dependencies with caching'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  cache-key-suffix:
    description: 'Additional suffix for cache key'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      shell: bash
      run: pip install poetry

    - name: Cache Poetry dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry
          ~/.poetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}${{ inputs.cache-key-suffix }}

    - name: Install dependencies
      shell: bash
      run: poetry install